### ISSUE TITLE
'process' variable?

### ISSUE THREAD

**Issue by Vossilisco** [charredgrass/nodejs-bot-guide#6]
Hi charredgrass,

First of all thank you so much for your repository, I am learning a lot.

I have a question about _login.js_ file.

```
... 
//logs in via browser
steam.login(logOnOptions, function(err, sessionID, cookies, steamguard) {
    if (err) {
        console.log("There was an error logging in! Error details: " + err.message);
        process.exit(1); //terminates program
} else { 
...
```

I cannot use **_process_** variable because it is unresolved for me and i don't know where do you declare it.

**Comment by andrewda** [comment]
`process` is not a variable and is never defined within the program. It is an object that provides information about, and control over, the current Node.js process. As a global, it is _always_ available to Node.js applications without using require(). `process.exit()` has been in NodeJS ever since v0.1.7.

There's obviously an issue with your setup if you're getting a `proccess is not defined` error. Check your NodeJS version with `node -v` and copy the result here. You should hopefully be using v4.4.4+.

**Comment by Vossilisco** [comment]
v4.4.7

And you are right, i have just rebuilt it since the beginning and it's working, it would be a noob error for sure.

Thank you!
